spring: 
  druid: 
  #datasource: 
    #eclipse启动的时候，默认加载的是target目录下的文件
    # :config  当前jar包所在目录下的config
    url: jdbc:sqlite:config/yx_image_recognition.db?date_string_format=yyyy-MM-dd HH:mm:ss
    username: sqlite
    password: sqlite
    driver-class-name: org.sqlite.JDBC
    max-active: 10 #最大连接数
    min-idle: 5 #最小连接数
    max-wait: 10000 #获取连接的最大等待时间
    time-between-eviction-runs-millis: 60000 #空闲连接的检查时间间隔
    min-evictable-idle-time-millis: 300000 #空闲连接最小空闲时间
 